services:
  - type: web
    name: moni-api
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node --enable-source-maps dist/index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: IDEMPOTENCY_TTL_SECONDS
        value: 86400
      - key: RATE_LIMIT_MAX
        value: 120
      - key: RATE_LIMIT_TIME_WINDOW
        value: 60000

